name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "home-assistant==2024.2.0"
          pip install pytest-homeassistant-custom-component
          pip install .[dev]

      - name: Run tests
        run: |
          pytest tests/ -v --cov=custom_components.cowboy
